### ISSUE TITLE
Should we deprecate this repository in favor of the official pebble?

### ISSUE THREAD

**Issue by tgalopin** [acmephp/testing-ca#12]
As @cpu proposed, it seems we could migrate to Let's Encrypt official pebble images (https://github.com/acmephp/testing-ca/pull/11#issuecomment-435393503).

What do you think @jderusse?

If we want to do remove this repo, we would probably need to deprecate it first and then remove it in a few months.

**Comment by jderusse** [comment]
Agreed. 

First, we have to move tests in acmephp repository

**Comment by jderusse** [comment]
fixed by  https://github.com/acmephp/acmephp/pull/183
