### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by kelunik** [acmephp/testing-ca#3]
How can I start the docker container so I can access port `4000`?

**Comment by jderusse** [comment]
The hardest part, is not accessing the CA certificate, (you can always bind port or use dns). It's, to let boulder to access your application to check the certificate.

The trick is to use use the net of your host with the option `--net host`. Look at the travis file on the symfony-bundle 
`docker run -d --name boulder --net host acmephp/testing-ca`

**Comment by kelunik** [comment]
Can't get it to work with https://github.com/kelunik/acme/blob/test-boulder/test/.run-boulder.sh

What's the directory address I have to use then?

**Comment by jderusse** [comment]
You have to provider your own web server to respond to challenge checks (listen to 127.0.0.1:5002)

A simple nginx should be enougth.

**Comment by kelunik** [comment]
Sure, but what's the directory URI of Boulder? http(s)?://127.0.0.1:4000/directory?

**Comment by jderusse** [comment]
No directory.

Just http://127.0.0.1:4000/

See the test configuration used in the AcmePhpBundle https://github.com/acmephp/symfony-bundle/blob/master/features/fixtures/TestApp/TestAppBundle/CertificateAuthority/Configuration/BoulderConfiguration.php

**Comment by kelunik** [comment]
Oh, thanks, got the actual error message now. What do I need to configure differently?

```
Waiting for debug port 8000


These processes exited early (check above for their output):
    'GORACE="halt_on_error=1" exec ./bin/boulder-sa --config /go/src/github.com/letsencrypt/boulder/test/boulder-config.json' with pid 738 exited 1
    'GORACE="halt_on_error=1" exec ./bin/ocsp-updater --config /go/src/github.com/letsencrypt/boulder/test/boulder-config.json' with pid 745 exited 1
    'GORACE="halt_on_error=1" exec ./bin/ocsp-responder --config /go/src/github.com/letsencrypt/boulder/test/boulder-config.json' with pid 748 exited 1
```

**Comment by kelunik** [comment]
Had a conflicting container running locally.

Directory was the expected `http://127.0.0.1/directory`, thanks for your help!
