### ISSUE TITLE
specific docker image tag

### ISSUE THREAD

**Issue by m59peacemaker** [acmephp/testing-ca#6]
Could you add a dockerhub hook that gives the image a specific tag rather than only `latest`?

**Comment by jderusse** [comment]
Whats is the point?q

**Comment by m59peacemaker** [comment]
I use the image for some tests. It seems like the same arguments would apply here as any other project dependency. Explicit versions avoid unexpected errors. If your image is updated and I run the tests on a machine that pulls the new image, my tests may fail even though I haven't changed anything.

**Comment by jderusse** [comment]
ping @tgalopin can you configure the docker hub registry ?

**Comment by tgalopin** [comment]
I created the tag 1.0.0: https://hub.docker.com/r/acmephp/testing-ca/tags/

**Comment by m59peacemaker** [comment]
@tgalopin @jderusse I get the following result using 1.0.0.

> > docker run --rm --net host -e BOULDER_CALLBACK_PORT=80 acmephp/testing-ca:1.0.0
> 
> sed: can't read test/boulder-config.json: No such file or directory
> sed: can't read test/boulder-config.json: No such file or directory
> sed: can't read test/boulder-config.json: No such file or directory
> sed: can't read test/boulder-config.json: No such file or directory
> Starting message broker: rabbitmq-server.
> Starting MariaDB database server: mysqld.
> Starting enhanced syslogd: rsyslogd.
> export GO15VENDOREXPERIMENT=1
> GOBIN=/go/src/github.com/letsencrypt/boulder/bin go install  ./...
> I034631 boulder-ra Versions: RA=(Unspecified Unspecified) Golang=(go1.5.4) BuildHost=(Unspecified)
> I034631 boulder-ra loading hostname policy, sha256: 3ddc932620e3f59623af52971fcc3cf38c9759f64575fd018a7097875427ea5e
> I034631 boulder-publisher Versions: Publisher=(Unspecified Unspecified) Golang=(go1.5.4) BuildHost=(Unspecified)
> I034631 boulder-ca Versions: CA=(Unspecified Unspecified) Golang=(go1.5.4) BuildHost=(Unspecified)
> Unable to create RA client: channel connect failed for WFE->RA.m59-VirtualBox.9a26b5: dial tcp 127.0.0.1:5673: getsockopt: connection refused
> I034631 boulder-wfe Versions: WFE=(Unspecified Unspecified) Golang=(go1.5.4) BuildHost=(Unspecified)
> E034631 boulder-wfe [AUDIT] Unable to create RA client: channel connect failed for WFE->RA.m59-VirtualBox.9a26b5: dial tcp 127.0.0.1:5673: getsockopt: connection refused
> I034631 boulder-ca loading hostname policy, sha256: 3ddc932620e3f59623af52971fcc3cf38c9759f64575fd018a7097875427ea5e
> E034631 boulder-ca [AUDIT] Couldn't load issuers: unable to load PKCS#11 module
> Couldn't load issuers: unable to load PKCS#11 module
> 
> These processes exited early (check above for their output):
>   'exec ./bin/boulder-wfe --config test/config/wfe.json' with pid 557 exited 1

**Comment by m59peacemaker** [comment]
I believe I see the problem. Since `boulder` is being cloned from github with at no specific tag or commit, the resulting image is likely to have bugs. 3 months ago when it was last built, the repository was in a stable state, and it seems not to be now. I would update the Dockerfile to use the latest release of boulder.

`git checkout tags/release-2016-07-14`

**Comment by m59peacemaker** [comment]
I will try to solve it and submit a pull request. That boulder release has the same problem...

**Comment by m59peacemaker** [comment]
The latest boulder commit that works with your Dockerfile is from 5/16/2016. Just in case it ever becomes important, the old build was from a commit on 4/21/2016.

**Comment by m59peacemaker** [comment]
https://github.com/acmephp/testing-ca/pull/7 locks down the boulder commit to the commit on 5/16

**Comment by tgalopin** [comment]
I published the new version as a working 1.0.0 tag.
